### ISSUE TITLE
[BUG] Broken link at https://microshift.io/docs/operations/usage/example-usage/

### ISSUE THREAD

**Issue by iranzo** [redhat-et/microshift-documentation#36]
https://microshift.io/docs/deployment-modes/quickstart-local/ has a side menu for 'Microshift Basic usage' that leads to https://microshift.io/docs/operations/usage/example-usage/ which is non existing

**Comment by cooktheryan** [comment]
@iranzo is this still there after the latest merge?

**Comment by iranzo** [comment]
Now, both URL's fail 😂

**Comment by iranzo** [comment]
Change in the url's, closing issue
