### ISSUE TITLE
[BUG] Add content for all `draft: true` files

### ISSUE THREAD

**Issue by sallyom** [redhat-et/microshift-documentation#56]
Documentation needs content for all files where `draft: true` is set. 
Set `draft: false` in the PR where content is added. 

Here is a search with the files that need content:
[https://github.com/redhat-et/microshift-documentation/search?q=%22draft%3A+true%22](https://github.com/redhat-et/microshift-documentation/search?q=%22draft%3A+true%22)

If working on a file, add a comment in this issue to avoid duplicating efforts.

**Comment by cooktheryan** [comment]
Deprecating for individual enhancements
