### ISSUE TITLE
RPM build 

### ISSUE THREAD

**Issue by marmendo** [redhat-et/microshift-documentation#93]
in:
https://microshift.io/docs/developer-documentation/build-install-rpm/#installing-the-rpms

This:
sudo dnf localinstall -y packaging/rpm/_rpmbuild/RPMS/x86_64/microshift-4.8.0-nightly.el8.x86_64.rpm

Should be:
sudo dnf localinstall -y packaging/rpm/_rpmbuild/RPMS/x86_64/microshift-4.8.0-nightly.*.x86_64.rpm

To avoid problems when building and running rpms on fedora.

**Comment by cooktheryan** [comment]
patched! Thank you!!
